apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-service
  namespace: argocd
spec:
  project: paxis-project
  source:
    repoURL: https://github.com/Projects-SelfPractices/argocd-ms-projects
    targetRevision: main
    path: api-service-gitops/base
  destination:
    server: https://kubernetes.default.svc
    namespace: api-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
